# Note:
# HARBOR_URL, HARBOR_USERNAME, HARBOR_TOKEN are defined at the organization level

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Harbor
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.HARBOR_URL  }}
          username: ${{ vars.HARBOR_USERNAME  }}
          password: ${{ secrets.HARBOR_TOKEN }}

      - name: Read env file
        uses: cardinalby/export-env-action@v2
        id: readEnvFile 
        with:
          envFile: '.env'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push (server)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.HARBOR_URL }}/ai4os/ai4os-cvat-backups:${{ env.VERSION }}
          file: Dockerfile
          build-args: |
            PYTHON_VERSION=${{ env.PYTHON_VERSION }}
            PYTHON_VERSION_MAJOR=${{ env.PYTHON_VERSION_MAJOR }}
            PYTHON_VERSION_MINOR=${{ env.PYTHON_VERSION_MINOR }}
            PYTHON_VERSION_PATCH=${{ env.PYTHON_VERSION_PATCH }}
